name: ControlGame
version: '1.0-SNAPSHOT'
main: me.geeklol.ControlGame.ControlGame
api-version: '1.21'
authors: [ geeklol ]
description: Control game

commands:
  drawpattern:
    usage: /<command> <x> <y> <z> <type corner if draw with corner mask>
    aliases: dp
  spawnboard:
    usage: /<command> <second player name>
    aliases: sb
  jointeam:
    usage: /join <team name red or blue>
  ap:
    usage: /ap
  vap:
    usage: /vap
  deleteapg:
    usage: /deleteapg
    aliases: del